// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebProjectCourse.Data;

#nullable disable

namespace WebProjectCourse.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230702214600_AddURLIMAGEM")]
    partial class AddURLIMAGEM
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebProjectCourse.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("OrdemDisplay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Ação",
                            OrdemDisplay = 1
                        },
                        new
                        {
                            Id = 2,
                            Nome = "SciFi",
                            OrdemDisplay = 2
                        },
                        new
                        {
                            Id = 3,
                            Nome = "História",
                            OrdemDisplay = 3
                        });
                });

            modelBuilder.Entity("WebProjectCourse.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListaPreco")
                        .HasColumnType("float");

                    b.Property<double>("Preco")
                        .HasColumnType("float");

                    b.Property<double>("Preco100")
                        .HasColumnType("float");

                    b.Property<double>("Preco50")
                        .HasColumnType("float");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UrlImagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Autor = "John Wick",
                            CategoriaId = 1,
                            Descricao = "Dont hurt the dog",
                            ISBN = "ABC1234567",
                            ListaPreco = 40.0,
                            Preco = 30.0,
                            Preco100 = 20.0,
                            Preco50 = 25.0,
                            Titulo = "The Continental",
                            UrlImagem = ""
                        },
                        new
                        {
                            Id = 2,
                            Autor = "Anakin Skywalker",
                            CategoriaId = 2,
                            Descricao = "The dark force awakens",
                            ISBN = "ATT8798789",
                            ListaPreco = 20.0,
                            Preco = 15.0,
                            Preco100 = 8.0,
                            Preco50 = 10.0,
                            Titulo = "Star Wars Tale",
                            UrlImagem = ""
                        },
                        new
                        {
                            Id = 3,
                            Autor = "Soldado Ryan",
                            CategoriaId = 3,
                            Descricao = "Pistola contra um tanque",
                            ISBN = "XZY46846",
                            ListaPreco = 45.0,
                            Preco = 30.0,
                            Preco100 = 24.0,
                            Preco50 = 28.0,
                            Titulo = "Segunda Guerra Mundial",
                            UrlImagem = ""
                        },
                        new
                        {
                            Id = 4,
                            Autor = "Maximus Decimus Meridius",
                            CategoriaId = 1,
                            Descricao = "Eu terei minha vingança",
                            ISBN = "AEC656454",
                            ListaPreco = 50.0,
                            Preco = 30.0,
                            Preco100 = 20.0,
                            Preco50 = 25.0,
                            Titulo = "Imperio Romano",
                            UrlImagem = ""
                        },
                        new
                        {
                            Id = 5,
                            Autor = "Miriam Smith",
                            CategoriaId = 2,
                            Descricao = "Viva ao imperador",
                            ISBN = "WH40000",
                            ListaPreco = 60.0,
                            Preco = 40.0,
                            Preco100 = 30.0,
                            Preco50 = 35.0,
                            Titulo = "WarHammer 40000",
                            UrlImagem = ""
                        });
                });

            modelBuilder.Entity("WebProjectCourse.Models.Produto", b =>
                {
                    b.HasOne("WebProjectCourse.Models.Produto", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
